### ISSUE TITLE
Error instantiating OverfeatTransformer

### ISSUE THREAD

**Issue by jrosebr1** [sklearn-theano/sklearn-theano#94]
I just pulled down the latest version of sklearn-theano from GitHub, installed it into my virtual environment, and then went to instantiate the `OverfeatTransformer` and got the following error:

<pre>>>> from sklearn_theano.feature_extraction import OverfeatTransformer
Using gpu device 0: GRID K520
>>> of = OverfeatTransformer(output_layers=[-3])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "sklearn_theano/feature_extraction/overfeat.py", line 298, in __init__
    detailed=detailed_network)
  File "sklearn_theano/feature_extraction/overfeat.py", line 253, in _get_fprop
    fprop = theano.function([input_var], expressions)
  File "/home/ubuntu/.virtualenvs/sktheano/local/lib/python2.7/site-packages/theano/compile/function.py", line 266, in function
    profile=profile)
  File "/home/ubuntu/.virtualenvs/sktheano/local/lib/python2.7/site-packages/theano/compile/pfunc.py", line 511, in pfunc
    on_unused_input=on_unused_input)
  File "/home/ubuntu/.virtualenvs/sktheano/local/lib/python2.7/site-packages/theano/compile/function_module.py", line 1466, in orig_function
    defaults)
  File "/home/ubuntu/.virtualenvs/sktheano/local/lib/python2.7/site-packages/theano/compile/function_module.py", line 1324, in create
    input_storage=input_storage_lists)
  File "/home/ubuntu/.virtualenvs/sktheano/local/lib/python2.7/site-packages/theano/gof/link.py", line 519, in make_thunk
    output_storage=output_storage)[:3]
  File "/home/ubuntu/.virtualenvs/sktheano/local/lib/python2.7/site-packages/theano/gof/vm.py", line 897, in make_all
    no_recycling))
  File "/home/ubuntu/.virtualenvs/sktheano/local/lib/python2.7/site-packages/theano/sandbox/cuda/__init__.py", line 259, in make_thunk
    compute_map, no_recycling)
  File "/home/ubuntu/.virtualenvs/sktheano/local/lib/python2.7/site-packages/theano/gof/op.py", line 739, in make_thunk
    output_storage=node_output_storage)
  File "/home/ubuntu/.virtualenvs/sktheano/local/lib/python2.7/site-packages/theano/gof/cc.py", line 1073, in make_thunk
    keep_lock=keep_lock)
  File "/home/ubuntu/.virtualenvs/sktheano/local/lib/python2.7/site-packages/theano/gof/cc.py", line 1015, in __compile__
    keep_lock=keep_lock)
  File "/home/ubuntu/.virtualenvs/sktheano/local/lib/python2.7/site-packages/theano/gof/cc.py", line 1442, in cthunk_factory
    key=key, lnk=self, keep_lock=keep_lock)
  File "/home/ubuntu/.virtualenvs/sktheano/local/lib/python2.7/site-packages/theano/gof/cmodule.py", line 1076, in module_from_key
    module = lnk.compile_cmodule(location)
  File "/home/ubuntu/.virtualenvs/sktheano/local/lib/python2.7/site-packages/theano/gof/cc.py", line 1354, in compile_cmodule
    preargs=preargs)
  File "/home/ubuntu/.virtualenvs/sktheano/local/lib/python2.7/site-packages/theano/sandbox/cuda/nvcc_compiler.py", line 434, in compile_str
    return dlimport(lib_filename)
  File "/home/ubuntu/.virtualenvs/sktheano/local/lib/python2.7/site-packages/theano/gof/cmodule.py", line 293, in dlimport
    rval = __import__(module_name, {}, {}, [module_name])
ImportError: ('The following error happened while compiling the node', GpuAlloc{memset_0=True}(CudaNdarrayConstant{0.0}, Shape_i{0}.0, Shape_i{0}.0, Elemwise{Composite{((((i0 + i1) - i2) // i3) + i4)}}.0, Elemwise{Composite{((((i0 + i1) - i2) // i3) + i4)}}.0), '\n', '/home/ubuntu/.theano/compiledir_Linux-3.13--generic-x86_64-with-Ubuntu-14.04-trusty-x86_64-2.7.6-64/tmpLNUEhc/87d76708312aab82a90a5274df9a9cc6.so: undefined symbol: _Z17CudaNdarray_SIZEtPK11CudaNdarray', '[GpuAlloc{memset_0=True}(CudaNdarrayConstant{0.0}, <TensorType(int64, scalar)>, <TensorType(int64, scalar)>, <TensorType(int64, scalar)>, <TensorType(int64, scalar)>)]')</pre>

Since it looks like a Theano error, I've included my Theano version as well:

`Theano==0.7.0`

Is there a dependency on `sklearn-theano` running on Theano 6.x?

**Comment by jrosebr1** [comment]
Answered my own question. It works fine using `Theano==0.6.0`.

**Comment by eickenberg** [comment]
Thanks for posting the issue. Glad you solved it for yourself.
But we have to look into this, since we'd prefer it to work on 0.7 and not
on 0.6 instead of vice versa ;)
I will try to reproduce as soon as I have a GPU back at hand, CPU seems to
work on both.

**Comment by nouiz** [comment]
This seem like a problem with the Theano cache or mixed Theano version
installed. Can you uninstall Theano many times to make sure all version are
removed. Theano delete your Theano cache (normally under ~/.theano on
linux). Then install 0.7.

**Comment by jthoth** [comment]
The same Trouble, Work after reinstall Theano..

**Comment by nouiz** [comment]
I would strongly suggest to try Theano 0.8.2, don't use older release.
There is very big update between Theano version.
