### ISSUE TITLE
OverfeatTransformer

### ISSUE THREAD

**Issue by DanlanChen** [sklearn-theano/sklearn-theano#98]
Hi, I am using this link:http://sklearn-theano.github.io/auto_examples/plot_asirra_dataset.html, but get this error: I do not know why?
tf = OverfeatTransformer(output_layers=[-3])

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home2/ift6ed05/anaconda2/lib/python2.7/site-packages/sklearn_theano-0.0.1-py2.7.egg/sklearn_theano/feature_extraction/overfeat.py", line 298, in __init__
    detailed=detailed_network)
  File "/home2/ift6ed05/anaconda2/lib/python2.7/site-packages/sklearn_theano-0.0.1-py2.7.egg/sklearn_theano/feature_extraction/overfeat.py", line 253, in _get_fprop
    fprop = theano.function([input_var], expressions)
  File "/home2/ift6ed05/.local/lib/python2.7/site-packages/theano/compile/function.py", line 317, in function
    output_keys=output_keys)
  File "/home2/ift6ed05/.local/lib/python2.7/site-packages/theano/compile/pfunc.py", line 479, in pfunc
    output_keys=output_keys)
  File "/home2/ift6ed05/.local/lib/python2.7/site-packages/theano/compile/function_module.py", line 1777, in orig_function
    defaults)
  File "/home2/ift6ed05/.local/lib/python2.7/site-packages/theano/compile/function_module.py", line 1641, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "/home2/ift6ed05/.local/lib/python2.7/site-packages/theano/gof/link.py", line 690, in make_thunk
    storage_map=storage_map)[:3]
  File "/home2/ift6ed05/.local/lib/python2.7/site-packages/theano/gof/vm.py", line 1037, in make_all
    no_recycling))
  File "/home2/ift6ed05/.local/lib/python2.7/site-packages/theano/gof/op.py", line 965, in make_thunk
    no_recycling)
  File "/home2/ift6ed05/.local/lib/python2.7/site-packages/theano/gof/op.py", line 879, in make_c_thunk
    output_storage=node_output_storage)
  File "/home2/ift6ed05/.local/lib/python2.7/site-packages/theano/gof/cc.py", line 1207, in make_thunk
    keep_lock=keep_lock)
  File "/home2/ift6ed05/.local/lib/python2.7/site-packages/theano/gof/cc.py", line 1152, in __compile__
    keep_lock=keep_lock)
  File "/home2/ift6ed05/.local/lib/python2.7/site-packages/theano/gof/cc.py", line 1602, in cthunk_factory
    key=key, lnk=self, keep_lock=keep_lock)
  File "/home2/ift6ed05/.local/lib/python2.7/site-packages/theano/gof/cmodule.py", line 1174, in module_from_key
    module = lnk.compile_cmodule(location)
  File "/home2/ift6ed05/.local/lib/python2.7/site-packages/theano/gof/cc.py", line 1513, in compile_cmodule
    preargs=preargs)
  File "/home2/ift6ed05/.local/lib/python2.7/site-packages/theano/gof/cmodule.py", line 2233, in compile_str
    return dlimport(lib_filename)
  File "/home2/ift6ed05/.local/lib/python2.7/site-packages/theano/gof/cmodule.py", line 331, in dlimport
    rval = __import__(module_name, {}, {}, [module_name])
ImportError: ('The following error happened while compiling the node', CorrMM{valid, (4, 4)}(Elemwise{Composite{(i0 * (i1 + i2))}}.0, Subtensor{::, ::, ::int64, ::int64}.0), '\n', '/home2/ift6ed05/.theano/compiledir_Linux-2.6-el6.x86_64-x86_64-with-redhat-6.1-Carbon-x86_64-2.7.11-64/tmpXsngiA/0abe6c2454e59eab7778e6c645d664c5.so: undefined symbol: sgemm_', '[CorrMM{valid, (4, 4)}(<TensorType(float32, 4D)>, <TensorType(float32, 4D)>)]')

**Comment by kastnerkyle** [comment]
Can you give me some more information about your platform / install setup?
